name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # TODO: add a build step here
      
      - name: Install Deno @1.32.5
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.32.5

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "lentg-fresh-blog-system"
          entrypoint: "./main.ts" # TODO: update entrypoint
